# Generated by Django 4.0.5 on 2022-09-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='social_lindin',
            new_name='socail_linkedin',
        ),
    ]
